[project]
name = "nuclearnormrec"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "cvxpy>=1.7.3",
    "ipykernel>=6.31.0",
    "matplotlib>=3.9.4",
    "ngsolve>=6.2.2506",
    "numpy>=2.0.2",
    "scipy>=1.13.1",
]
